// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4F3qXFmDMbyBwI7y_7-GD3dJ038NUab4',
    appId: '1:470598546546:web:56c37c50cc309bf5c47eeb',
    messagingSenderId: '470598546546',
    projectId: 'fir-chat-236f0',
    authDomain: 'fir-chat-236f0.firebaseapp.com',
    storageBucket: 'fir-chat-236f0.appspot.com',
    measurementId: 'G-GRWH3TQTRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeQR-d7hheFhvVu4cP3RhzQL5x92k972U',
    appId: '1:470598546546:android:a1e709b45125449bc47eeb',
    messagingSenderId: '470598546546',
    projectId: 'fir-chat-236f0',
    storageBucket: 'fir-chat-236f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCROhjrs4TRhnBEqw1-FoaAaqo9yqEuLP8',
    appId: '1:470598546546:ios:aa7d11e548ea832ec47eeb',
    messagingSenderId: '470598546546',
    projectId: 'fir-chat-236f0',
    storageBucket: 'fir-chat-236f0.appspot.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCROhjrs4TRhnBEqw1-FoaAaqo9yqEuLP8',
    appId: '1:470598546546:ios:f3421339c3c0725cc47eeb',
    messagingSenderId: '470598546546',
    projectId: 'fir-chat-236f0',
    storageBucket: 'fir-chat-236f0.appspot.com',
    iosBundleId: 'com.example.firebaseChat.RunnerTests',
  );
}
